### PR TITLE
Add the CSV hash table in Hash layer and fix a bug.

### PR DESCRIPTION
**Pull request by dengc367**
* delete the Lambda sublayer in LocalActivationUnit Layer class

* add vocabulary_path in the SparseFeat to support the csv HashTable functionality

* update docs and add examples in doc

* Remove trailing whitespace

### CODE REVIEW

**Comment by dengc367** [comment]
this PR will be merged into `release` branch, and so you need merge into `master` branch when this PR is merged. @shenweichen

**Comment by dengc367** [comment]
I added some pytest code of hash vocabulary_path parameter

**Comment by dengc367** [comment]
@shenweichen I used your `layer_test` function in `pytest`, and when that run the line `model.predict` and throws the exception ` Failed precondition: Table not initialized.`, I think the `pytest` environment is the `tfv1`.

**Comment by dengc367** [comment]
It's strange, I have tested successfully in my local linux, but it always failed when using CI action with exception: `Failed precondition: Table not initialized.`. 
image

**Comment by shenweichen** [comment]
> @shenweichen I used your `layer_test` function in `pytest`, and when that run the line `model.predict` and throws the exception ` Failed precondition: Table not initialized.`, I think the `pytest` environment is the `tfv1`.

i think you need to  test it in your local machine in both `tf1` and `tf2`

**Comment by dengc367** [comment]
I have modified some code to fix a bug `An op outside of the function building code is being passed a "Graph" tensor` in `PostionalEncoding` Layer, which substituted the `tf.concat` with `np.zeros` when `zero_pad`=`True`, and remove the `tf.compat.v1.disable_eager_execution()` in `sequence_test.py`, so all the unit tests are successfully.

**Comment by shenweichen** [comment]
committers are not allowed to merge their own branches to release, we will review your pull request soon.

**Comment by dengc367** [comment]
OK

**Pull request merged**
