### PR TITLE
Fwfm

### PR DESCRIPTION
**Pull request by pandeconscious**
Support for Field-weighted Factorization Machines for Click-Through Rate Prediction in Display Advertising

[WWW 2018][Field-weighted Factorization Machines for Click-Through Rate Prediction in Display Advertising](https://arxiv.org/pdf/1806.03514.pdf)

### CODE REVIEW

**Comment by shenweichen** [comment]
have you test the Fwfm model you write on public dataset like kaggle avazu ctr data and observe the performence between it and other models

**Comment by pandeconscious** [comment]
Yes, the performance on Avau and Criteo datasets are:

**Avazu:** AUC: 0.7768,  Log Loss: 0.3814
**Criteo:** AUC: 0.8102,  Log Loss: 0.4415

90:10:10 - train:validate:test

The comparison with other models is similar (sometimes even better with hyperparameter tuning) as claimed in the FwFM paper by the authors.

**Comment by shenweichen** [comment]
ok
since committing a merge directly to the `master` branch is prohibited,please open a pull request on `release`  branch and merge your pr by **Squash and merge** button

**Comment by pandeconscious** [comment]
Cool, this has been done: https://github.com/shenweichen/DeepCTR/pull/237

**Pull request closed without merging**
