### PR TITLE
FEFM/DeepFEFM

### PR DESCRIPTION
**Pull request by pandeconscious**
Support for FEFM and DeepFEFM

[Field-Embedded Factorization Machines for Click-through rate prediction ](https://arxiv.org/abs/2009.09931 )

The results in the paper were generated using the same codebase. Thus they are tested for the same numbers as in the paper.

### CODE REVIEW

**Comment by shenweichen** [comment]
@pandeconscious  the CI was  failling, please fix that 
image

**Comment by pandeconscious** [comment]
@shenweichen this error seems to be related to this change: https://github.com/shenweichen/DeepCTR/commit/c98a78383771235eaa97efe94f9f0065fc21ee19

**Comment by pandeconscious** [comment]
@shenweichen can you take a look now at this PR?

**Review by shenweichen — APPROVED** [review]
The value of this `embedding_size` of `DeepFEFM` can be inferred from the shape of the input tensor. I will update the logic after PR  has been merged.

**Comment by gauravbrills** [comment]
@shenweichen  @pandeconscious  for DeepFEFM are sparse features required I usually get this error 

```
[/usr/local/lib/python3.8/dist-packages/deepctr/models/deepfefm.py](https://localhost:8080/#) in DeepFEFM(linear_feature_columns, dnn_feature_columns, use_fefm, dnn_hidden_units, l2_reg_linear, l2_reg_embedding_feat, l2_reg_embedding_field, l2_reg_dnn, seed, dnn_dropout, exclude_feature_embed_in_dnn, use_linear, use_fefm_embed_in_dnn, dnn_activation, dnn_use_bn, task)
     59                                                                         seed, support_group=True)
     60 
---> 61     fefm_interaction_embedding = concat_func([FEFMLayer(
     62         regularizer=l2_reg_embedding_field)(concat_func(v, axis=1))
     63                                               for k, v in group_embedding_dict.items() if k in [DEFAULT_GROUP_NAME]],

[/usr/local/lib/python3.8/dist-packages/deepctr/layers/utils.py](https://localhost:8080/#) in concat_func(inputs, axis, mask)
    185         return inputs[0]
    186     else:
--> 187         return tf.keras.layers.Concatenate(axis=axis)(inputs)
    188 
    189 

[/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py](https://localhost:8080/#) in __call__(self, *args, **kwargs)
   1021       with ops.name_scope_v2(name_scope):
   1022         if not self.built:
-> 1023           self._maybe_build(inputs)
   1024 
   1025         if self._autocast:

[/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py](https://localhost:8080/#) in _maybe_build(self, inputs)
   2623         # operations.
   2624         with tf_utils.maybe_init_scope(self):
-> 2625           self.build(input_shapes)  # pylint:disable=not-callable
   2626       # We must set also ensure that the layer is marked as built, and the build
   2627       # shape is stored since user defined build functions may not be calling

[/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/utils/tf_utils.py](https://localhost:8080/#) in wrapper(instance, input_shape)
    268     if input_shape is not None:
    269       input_shape = convert_shapes(input_shape, to_tuples=True)
--> 270     output_shape = fn(instance, input_shape)
    271     # Return shapes from `fn` as TensorShapes.
    272     if output_shape is not None:

[/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/layers/merge.py](https://localhost:8080/#) in build(self, input_shape)
    487   def build(self, input_shape):
    488     # Used purely for shape validation.
--> 489     if not isinstance(input_shape[0], tuple) or len(input_shape) < 1:
    490       raise ValueError('A `Concatenate` layer should be called '
    491                        'on a list of at least 1 input.')
```

**Pull request merged**
